name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Test with pytest
      run: |
        pip install -r requirements.txt
        PYTHONPATH=src py.test -o log_cli=true tests/
